/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Application.form;

import View.aplicacion.Application;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author gyaci
 */
public class nosotross extends javax.swing.JPanel {

    /**
     * Creates new form nosotross
     */
    public nosotross() {
        initComponents();
        
        lbNosotros.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font;");
        
        //MISION
        lbMision.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font;");
        lbMision1.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h3.font;");
        lbMision2.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h3.font;");
        lbMision3.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h3.font;");
        
        lbMision.setText("Nuestra Misión");
        
        Panel1.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:50;"
                + "background:lighten(@background,5%);");
        
        //VISION
        lbVision.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font;");
        lbVision1.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h3.font;");
        lbVision2.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h3.font;");
        lbVision3.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h3.font;");
        
        lbVision.setText("Nuestra Visión");
        
        Panel2.putClientProperty(FlatClientProperties.STYLE, ""
                + "arc:50;"
                + "background:lighten(@background,5%);");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNosotros = new javax.swing.JLabel();
        btnLogin = new View.BotonLogin.boton3();
        btnNosotros = new View.BotonLogin.boton3();
        jLabel1 = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        lbMision = new javax.swing.JLabel();
        lbMision1 = new javax.swing.JLabel();
        lbMision2 = new javax.swing.JLabel();
        lbMision3 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        lbVision = new javax.swing.JLabel();
        lbVision1 = new javax.swing.JLabel();
        lbVision2 = new javax.swing.JLabel();
        lbVision3 = new javax.swing.JLabel();

        lbNosotros.setText("SOBRE NOSOTROS");

        btnLogin.setForeground(new java.awt.Color(102, 102, 102));
        btnLogin.setText("Inicio Sesión");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        btnNosotros.setForeground(new java.awt.Color(102, 102, 102));
        btnNosotros.setText("Sobre Nosotros");
        btnNosotros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNosotrosMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/png/nosotros.gif.gif"))); // NOI18N

        lbMision.setText("jLabel2");

        lbMision1.setText("Somos una comunidad de salesianos consagrados");

        lbMision2.setText("que, corresponsablemente con laicos,");

        lbMision3.setText("nos dedicamos a educar y evangelizar ");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMision3)
                    .addComponent(lbMision2)
                    .addComponent(lbMision1)
                    .addComponent(lbMision))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbMision)
                .addGap(18, 18, 18)
                .addComponent(lbMision1)
                .addGap(18, 18, 18)
                .addComponent(lbMision2)
                .addGap(18, 18, 18)
                .addComponent(lbMision3)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lbVision.setText("jLabel2");

        lbVision1.setText("Al año 2022 ser identificados en Centroamérica por:");

        lbVision2.setText("La corresponsabilidad entre salesianos y laicos");

        lbVision3.setText("La significatividad de sus obras.");

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVision3)
                    .addComponent(lbVision2)
                    .addComponent(lbVision1)
                    .addComponent(lbVision))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbVision)
                .addGap(18, 18, 18)
                .addComponent(lbVision1)
                .addGap(18, 18, 18)
                .addComponent(lbVision2)
                .addGap(18, 18, 18)
                .addComponent(lbVision3)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNosotros)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNosotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbNosotros)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 152, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNosotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNosotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNosotrosMouseClicked
        // TODO add your handling code here:
        Application.nosotross();
    }//GEN-LAST:event_btnNosotrosMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        Application.logout();
    }//GEN-LAST:event_btnLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private View.BotonLogin.boton3 btnLogin;
    private View.BotonLogin.boton3 btnNosotros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbMision;
    private javax.swing.JLabel lbMision1;
    private javax.swing.JLabel lbMision2;
    private javax.swing.JLabel lbMision3;
    private javax.swing.JLabel lbNosotros;
    private javax.swing.JLabel lbVision;
    private javax.swing.JLabel lbVision1;
    private javax.swing.JLabel lbVision2;
    private javax.swing.JLabel lbVision3;
    // End of variables declaration//GEN-END:variables
}
