/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Application.form;

import java.io.ByteArrayOutputStream;
import javax.swing.ImageIcon;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

public class RecuSMS extends javax.swing.JPanel {

    /**
     * Creates new form RecuSMS
     */
    public RecuSMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        btnRegresosms = new javax.swing.JButton();
        label1 = new java.awt.Label();
        txtTelefono = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        btnRestablecer = new javax.swing.JButton();
        label4 = new java.awt.Label();
        txtCambioContraseña = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresosms.setBackground(new java.awt.Color(0, 51, 102));
        btnRegresosms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/png/regreso (3).png"))); // NOI18N
        add(btnRegresosms, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 37));

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setForeground(java.awt.Color.lightGray);
        label1.setText("Ingrese la nueva contraseña:");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));
        label1.getAccessibleContext().setAccessibleName("");

        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 390, -1));

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setForeground(java.awt.Color.lightGray);
        label2.setText("Genere el cogido y escaneleo para iniciar con el proceso de recuperacion ");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        btnRestablecer.setBackground(new java.awt.Color(0, 51, 102));
        btnRestablecer.setForeground(new java.awt.Color(255, 255, 255));
        btnRestablecer.setText("Restablecer");
        add(btnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 130, 50));

        label4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label4.setForeground(java.awt.Color.lightGray);
        label4.setText("Ingrese el codigo que se genero");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));
        add(txtCambioContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 390, -1));

        btnEnviar.setBackground(new java.awt.Color(0, 51, 102));
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Generar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 110, 50));
        add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 240, 200));

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        jScrollPane1.setViewportView(txtTexto);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 250, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/png/QR Code-amico (3).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
         ByteArrayOutputStream out = QRCode.from(this.txtTexto.getText()).to(ImageType.PNG).stream();
        ImageIcon imageIcon = new ImageIcon(out.toByteArray());
        this.lblImagen.setIcon(imageIcon);
    }//GEN-LAST:event_btnEnviarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRegresosms;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtCambioContraseña;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables
}
