/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Application.form.other;

import com.formdev.flatlaf.FlatClientProperties;
import java.text.SimpleDateFormat;
import java.util.*;

public class PantallaInicio extends javax.swing.JPanel implements Runnable {
 int hora,minutos,segundos; 
    String timestr, yearstr; 
    int day,month,year;
    
    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        Thread t= new Thread(this);
        t.start();
        initComponents();
        time.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        date.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("A");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 644, 50));

        date.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("A");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 640, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/png/pila-libros-tapa-dura-contra-fondo-blanco-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 43, 410, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
        try{
            Calendar c=Calendar.getInstance();
            hora=c.get(Calendar.HOUR_OF_DAY);
            if(hora>12)
                hora = hora-12;
            minutos=c.get(Calendar.MINUTE);
            segundos=c.get(Calendar.SECOND);
            year=c.get(Calendar.YEAR);
            month=c.get(Calendar.MONTH);
            day=c.get(Calendar.DAY_OF_MONTH);
            SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
            SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
            Date dat=c.getTime() ;
            timestr=sdf.format(dat);
            yearstr=df.format(dat);
            time.setText(timestr);
            date.setText(yearstr);
        }catch (Exception e ){
            e.printStackTrace();
        }
    }}
}
